.TH WOYF 1 2022-06-24 woyf\-VERSION
.SH NAME
woyf \- watch over your files
.SH SYNOPSIS
.B woyf
COMMAND [\fIARGS...\fR]
.SH DESCRIPTION
This program executes a COMMAND with the given ARGS when a FILE
changes.
.br
FILEs are supplied on the standard input with one FILE per line. The
list must be ended by an EOF character.
.br
When a file changes, the program displays a message of the form `woyf:
file FILE has changed` on the standard error file.
.SH EXAMPLES
$ echo "main.c" | ./woyf make all
.SH AUTHORS
Written by Gustek \<gustek@riseup.net\>.
.SH SEE ALSO
stat(3)
