.TH WOYF 1 2022-06-24 woyf\-VERSION
.SH NAME
woyf \- watch over your files
.SH SYNOPSIS
.B woyf
COMMAND [\fIARGS...\fR]
.SH DESCRIPTION
This program executes a COMMAND with the given ARGS when a FILE
changes.
.br
This program watches over the following events:
.br
	- Creation of a file inside a directory.
.br
	- Deletion of a file inside a directory.
.br
	- Deletion of a FILE.
.br
	- Modification of a file.

FILEs are supplied on the standard input with one FILE per line.
.br
The list must be ended by an EOF character. A FILE can either be a
regular file or a directory.
.SH EXAMPLES
$ find ./ -name '*.c' -type f | ./woyf make all
.SH AUTHORS
Written by Gustek \<gustek@riseup.net\>.
.SH SEE ALSO
inotify(7)
